# Generated by Django 2.1 on 2018-08-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20180816_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_user',
            name='re_password',
        ),
        migrations.AlterField(
            model_name='register_user',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
