# Generated by Django 2.1 on 2018-08-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20180816_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='register_pg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('no_of_pg', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='register_user',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='register_user',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='register_user',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
